### ISSUE TITLE
打开地址就报错

### ISSUE THREAD

**Issue by github653224** [small99/AutoLink#9]
![image](https://github.com/small99/AutoLink/assets/20598377/5f85d53a-0233-49a0-8189-6b71fcb703f7)

Exception
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.

Traceback (most recent call last)
File "/Users/apple/.virtualenvs/autoLinkEnv/lib/python3.9/site-packages/flask/app.py", line 2213, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/apple/.virtualenvs/autoLinkEnv/lib/python3.9/site-packages/flask/app.py", line 2193, in wsgi_app
response = self.handle_exception(e)
File "/Users/apple/.virtualenvs/autoLinkEnv/lib/python3.9/site-packages/flask_restful/__init__.py", line 298, in error_router
return original_handler(e)
File "/Users/apple/.virtualenvs/autoLinkEnv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/Users/apple/.virtualenvs/autoLinkEnv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/apple/.virtualenvs/autoLinkEnv/lib/python3.9/site-packages/flask_restful/__init__.py", line 298, in error_router
return original_handler(e)
File "/Users/apple/.virtualenvs/autoLinkEnv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/apple/.virtualenvs/autoLinkEnv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/Users/apple/Documents/AutoLink-master/auto/www/blueprints.py", line 30, in index
return render_template('login.html')
File "/Users/apple/.virtualenvs/autoLinkEnv/lib/python3.9/site-packages/flask/templating.py", line 151, in render_template
return _render(app, template, context)
File "/Users/apple/.virtualenvs/autoLinkEnv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
app.update_template_context(context)
File "/Users/apple/.virtualenvs/autoLinkEnv/lib/python3.9/site-packages/flask/app.py", line 737, in update_template_context
context.update(func())
File "/Users/apple/.virtualenvs/autoLinkEnv/lib/python3.9/site-packages/flask_login/utils.py", line 407, in _user_context_processor
return dict(current_user=_get_user())
File "/Users/apple/.virtualenvs/autoLinkEnv/lib/python3.9/site-packages/flask_login/utils.py", line 372, in _get_user
current_app.login_manager._load_user()
File "/Users/apple/.virtualenvs/autoLinkEnv/lib/python3.9/site-packages/flask_login/login_manager.py", line 347, in _load_user
raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info. 
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame

**Comment by github653224** [comment]
加了这个登录又报错415了
![image](https://github.com/small99/AutoLink/assets/20598377/b81c9396-f85f-4f52-aa63-acc0b0cf2386)


![image](https://github.com/small99/AutoLink/assets/20598377/a1ea0a82-a555-4b57-9fde-b0383bc2391c)
